// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	RoleType int    `json:"role_type"`
}

type UserRegisterData struct {
	UserId int64 `json:"user_id"`
}

type UserRegisterRes struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data UserRegisterData `json:"data"`
}
