// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCourse = "courses"

// Course 课程表
type Course struct {
	CourseID    int64   `gorm:"column:course_id;type:int(11);primaryKey;autoIncrement:true;comment:课程ID" json:"course_id"` // 课程ID
	UserID      int64   `gorm:"column:user_id;type:int(11);not null;comment:用户ID" json:"user_id"`                          // 用户ID
	CourseName  string  `gorm:"column:course_name;type:varchar(100);not null;comment:课程名称" json:"course_name"`             // 课程名称
	Description string  `gorm:"column:description;type:varchar(100);not null;comment:课程描述" json:"description"`             // 课程描述
	Price       float64 `gorm:"column:price;type:decimal(10,2);not null;default:0.00;comment:课程价格" json:"price"`           // 课程价格
	CreatedAt   int64   `gorm:"column:created_at;type:int(11);not null;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt   int64   `gorm:"column:updated_at;type:int(11);not null;comment:更新时间" json:"updated_at"`                    // 更新时间
	Status      int64   `gorm:"column:status;type:int(11);not null;comment:状态:0正常、1禁用" json:"status"`                      // 状态:0正常、1禁用
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
