// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go_project/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users/register",
				Handler: UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/updatePassword",
				Handler: UserUpdatePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/deleteUserById",
				Handler: AdminDeleteUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/getUserList",
				Handler: GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/addCourse",
				Handler: AdminAddCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/updateCourse",
				Handler: AdminUpdateCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/delCourse",
				Handler: AdminDelCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/getCourseList",
				Handler: GetCourseListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/addCategory",
				Handler: AdminAddCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/updateCategory",
				Handler: AdminUpdateCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/bindCourseCategory",
				Handler: AdminBindCourseCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/delCategory",
				Handler: AdminDelCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/getCategoryList",
				Handler: GetCategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/placeOrder",
				Handler: PlaceOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/getOrderList",
				Handler: GetOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/cancelOrder",
				Handler: CancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/orderInfo",
				Handler: OrderInfoHandler(serverCtx),
			},
		},
	)
}
